# Generated by Django 3.1.6 on 2021-02-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210215_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('NONE', 'None'), ('WHITE', 'White'), ('BLACK', 'Black'), ('PINK', 'Pink'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('GREY', 'Grey'), ('RED', 'Red'), ('GREEN', 'Green'), ('PURPLE', 'Purple'), ('ORANGE', 'Orange')], default=('NONE', 'None'), max_length=50),
        ),
    ]
