# Generated by Django 3.1.6 on 2021-02-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210222_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CANI', 'Căni'), ('BORCANE', 'Borcane'), ('PAHARE', 'Pahare'), ('BIJUTERII', 'Bijuterii'), ('FIGURINE', 'Figurine'), ('TERMOSURI', 'Termosuri'), ('ALBUME', 'Albume foto'), ('ALTELE', 'Alte obiecte')], default=('ALTELE', 'Alte obiecte'), max_length=100),
        ),
    ]
