# Generated by Django 3.1.6 on 2021-03-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('NONE', 'none'), ('ALB', 'alb'), ('NEGRU', 'negru'), ('ROZ', 'roz'), ('ALBASTRU', 'albastru'), ('GALBEN', 'galben'), ('GRI', 'gri'), ('ROSU', 'rosu'), ('VERDE', 'verde'), ('MOV', 'mov'), ('PORTOCALIU', 'portocaliu')], default=('NONE', 'none'), max_length=50),
        ),
    ]
